### ISSUE TITLE
M3D Profile auto-default, won't let me set any others .

### ISSUE THREAD

**Issue by SechyMonkey** [donovan6000/M33-Fio#163]
I had an existing installation of OctoPrint on Raspberry Pi Jessie. Using the Plugin Manager, I installed M3D-Fio version 0.35. After installing, it set the new profile that was created for the M3D Micro to default, and it will not allow me to set my Taz 5 profile that was already there back to default.

**Comment by donovan6000** [comment]
Make sure you have the newest version of M33 Fio installed, V1.2, and that you have the 'Not using a Micro 3D printer' option enable. That should allow you to set the default profile and use other printers while M33 Fio is installed.
![other](https://cloud.githubusercontent.com/assets/6620767/17049194/aac873f0-4fa0-11e6-9dbe-fa5db2a92f4d.png)

**Comment by donovan6000** [comment]
It's been a while since anyone has responded to this issue, so I'll probably close it in a couple of days. Let me know if you still have any interest in testing/fixing this issue.
