### ISSUE TITLE
New version of M3D firmware

### ISSUE THREAD

**Issue by abbradar** [donovan6000/M33-Fio#213]
I've installed firmware V2016040402 from official M3D Linux. In M33-Fio only V2016040401 is available.

**Comment by donovan6000** [comment]
V2016040402 is 100% identical to V2016040401. All of M3D's macOS and Windows software that came out after their Linux software have all used the version number V2016040401, so I've stuck to using that version number in M33 Fio.

**Comment by abbradar** [comment]
Oh, strange that they have two identical releases. Anyway, thanks for clarification!
