### ISSUE TITLE
No access to slicer profile editor 

### ISSUE THREAD

**Issue by Fullmono** [donovan6000/M33-Fio#219]
Hi, 

Since a while, I don't have access to slicer profile editor.
I mean, I upload a stl object, I click on slice button, give gcode name and my model is sliced without any questions. I can't edit slicer profile, I can't move and edit my model, ... 
I( happened after octoprint update. 
Any idea withtout re-install octoprint? 
( I did update octoprint, m33-fio, ...)

Regards

**Comment by donovan6000** [comment]
It should be working with the newest release, [V1.18](https://github.com/donovan6000/M33-Fio/releases/tag/V1.18). Older versions of M33 Fio aren't compatible with OctoPrint V1.3.2.
