### ISSUE TITLE
Backlash calibration not starting on 1.18

### ISSUE THREAD

**Issue by pusaken** [donovan6000/M33-Fio#222]
Hello everyone,

I didn't try with previous version, but with 1.18 I don't seem to be able to start backlash calibration.
The How-To window appears, and so does the next ("print status") asking me for material and temperature. But after clicking "Print" nothing happens.

Anyone else having this issue?

Regards,
pusaken

**Comment by Fullmono** [comment]
I confirm

**Comment by donovan6000** [comment]
Its working again in [V1.19](https://github.com/donovan6000/M33-Fio/releases/tag/V1.19).
