### ISSUE TITLE
Custom control disappear

### ISSUE THREAD

**Issue by Fullmono** [donovan6000/M33-Fio#223]
I don't have access to "custom controls" pannel (calibration, every control made for m3d...) anymore .
I did try to reinstall M33 but it didn't work.

I don't understand why, the controls were present yesterday!

**Comment by donovan6000** [comment]
Make sure to disable the Settings > M33 Fio > 'Not using a Micro 3D printer'. M33 Fio V1.18 has that setting enabled by default since it was it was inconveniencing all the M33 Fio users who aren't using Micro 3D printers.

**Comment by donovan6000** [comment]
Looks like there's a problem with M33 Fio's JavaScript. Can you post any error messages that you see in your web browser JavaScript console? You can get the the console by right clicking on the page and choosing an options that's similar to 'Inspect Element'. That should open a window that has an option similar to 'Console' that shows if there's any JavaScript errors.
![console](https://cloud.githubusercontent.com/assets/6620767/25933406/65d8c864-35cb-11e7-9d7c-aea33b0bcb7e.png)

**Comment by Fullmono** [comment]
You are right:

![screenshot 2017-05-12 at 20 07 50](https://cloud.githubusercontent.com/assets/4299889/26010973/645198b0-374f-11e7-8ad2-b4899f122572.png)

**Comment by donovan6000** [comment]
@Fullmono I think something got messed up with your OctoPrint installation. The gcodeViewModel is one of the view models that OctoPrint has always provided. Try reinstalling OctoPrint and that should fix the issue..
