### ISSUE TITLE
Fio causing WebGL to crash

### ISSUE THREAD

**Issue by fooforever** [donovan6000/M33-Fio#231]
Just performing a new install of octoprint on a raspberry pi, using the latest octopi image. After installing the Fio plugin chrome hangs when loading the octoprint page  then webgl crashes. There doesn't seem to be anything printed in any of the debug logs found in the octoprint menus.

Using Chrome 59 on Arch Linux

![screenshot from 2017-06-21 20-18-39](https://user-images.githubusercontent.com/665772/27402535-da3857ce-56be-11e7-949b-49ee595bcc51.png)

**Comment by donovan6000** [comment]
Are there any JavaScript errors reported in Chrome's console. You can view it by right clicking anywhere, choosing 'Inspect', and then going to the 'Console tab'.
![console](https://user-images.githubusercontent.com/6620767/27416057-eb78301c-56bf-11e7-8ee3-6e87bf89d563.png)

Also are you experiencing this in any other web browsers, or just Chrome?

**Comment by fooforever** [comment]
Sorry @donovan6000 erm it appears to have started to work again.just logged in again to check for errors and its fine.

**Comment by donovan6000** [comment]
It's alright. Glad everything's working again.
