### ISSUE TITLE
Cant connect to printer

### ISSUE THREAD

**Issue by liviagh** [donovan6000/M33-Fio#232]
Hello everyone, 

When trying to connect to the printer the following message is displayed :There was an unhandled error while talking to the printer. Due to that OctoPrint disconnected. Error: Connection error, see Terminal tab. Attached you will see a screenshot. 
<img width="1261" alt="screen shot 2017-06-27 at 21 30 20" src="https://user-images.githubusercontent.com/22915354/27606292-fec65ec2-5b7f-11e7-83f5-3564e9c34fc7.png">
<img width="1238" alt="screen shot 2017-06-27 at 22 02 05" src="https://user-images.githubusercontent.com/22915354/27607489-531eeb5c-5b84-11e7-9b03-ea9f88ddf5ff.png">

In the octopi terminal is the following:Connecting to: /dev/tty1
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x6dedc930, open=True>(port='/dev/tty1', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: N0 M110 N0*125
There was a timeout while trying to connect to the printer
Changing monitoring state from 'Connecting' to 'Offline'
Connection closed, closing down monitor

In the raspbery terminal i receive the message N0 M110 N0*125. Does anyone know what might cause this issue? 

....

Problem solved, the port was not selected correctly and the bau rate is for my wanhao 115200.

**Comment by donovan6000** [comment]
Glad you got it working.

Also I'm not quite sure why you reported this in the M33 Fio repository. Those screenshots indicate that you don't even have the M33 Fio plugin installed.
