### ISSUE TITLE
Model Editor doesn't show Next or Cancel buttons

### ISSUE THREAD

**Issue by aliban** [donovan6000/M33-Fio#233]
Hello

 I'm using OctoPi Version 1.3.4 (master branch) with M33 FIO 1.20 and with Firefox or Safari the model editor doesn't show Next or Cancel buttons, even if I chose skip Model Editor, the Model Editor will load. Any advice on how to fix it?

**Comment by donovan6000** [comment]
Try using the newest version of M33 Fio, [V1.21](https://github.com/donovan6000/M33-Fio/releases/tag/V1.21), and let me know if you still experience this issue.
