### ISSUE TITLE
Extracting and uploading firmware failed

### ISSUE THREAD

**Issue by dylanmtaylor** [donovan6000/M33-Fio#235]
I have an original micro (I backed the project), and I tried to upload my bootloader but it just comes back saying this failed. Updating iME shows as success but I can't seem to connect to the printer.

**Comment by donovan6000** [comment]
What operating system are you using, what version of M33 Fio are you using, and what version of OctoPrint are you using?

**Comment by dylanmtaylor** [comment]
Raspbian 8.0 Jessie - OctoPi premade distribution on a Pi Zero W. OctoPrint version : 1.3.4
OctoPi version    : 0.14.0 M33 Fio version : 1.21

**Comment by donovan6000** [comment]
Can you upload your OctoPrint log so we can see if it contains any errors related to M33 Fio? You can get it it at Settings > Log > octoprint.log.
![log](https://user-images.githubusercontent.com/6620767/27112806-2fd5f4ea-506e-11e7-8fcc-6d52adab03a5.png)
